apiVersion: v1
kind: Service
metadata:
  name: workfront-service
spec:
  selector:
    app: workfront        # This must match the label in your deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80            # Port your service exposes
      targetPort: 5000    # Port your container listens on
      nodePort: 30007     # External port to access the app (optional range: 30000–32767)
